### ISSUE TITLE
[FEATURE] Criar módulo de Base Técnica

### ISSUE THREAD

**Issue by angelinopires** [angelinopires/career_rush#4]
Nesse módulo vamos abordar os principais conceitos mais básicos de tecnologia. 

Como o foco desse guia é possibilitar que as pessoas trabalhem com **Desenvolvimento WEB**, os tópicos que serão descritos vão ser sobre esse assunto.

Principais tópicos:

- Algoritmos e Lógica de Programação;
- Principais ferramentas de trabalho;
- GIT;
- Bash (Terminal);
- Qual é a real função de um(a) profissional desenvolvedor(a).

Como cada um desses assunto pode ser um tópico mais extenso e bem detalhado, com objetivos e recompensas, seria interessante eles possuírem seu próprio arquivo de _Markdown_.

**Comment by juunegreiros** [comment]
Gosto bastante do [Developers Roadmap](https://github.com/kamranahmedse/developer-roadmap), acha válido nos basearmos neles para os tópicos?

**Comment by juunegreiros** [comment]
De conteúdo técnico web, no caso. Acho que tanto algoritmos e Lógica, Bash e Qual a real função de um programador não são específicos para desenvolvedores Web (podem ser usados em vários outros lugares). Inclusive pro último tópico (Qual é a real função de um(a) profissional desenvolvedor(a)) podemos colocar em um módulo de carreira mesmo, explicando quais as funções de cada área e cargo, numa visão mais geral.

**Comment by angelinopires** [comment]
É o plano explicar cada uma dessas coisas @juunegreiros.

Talvez esse módulo que fale sobre carreia faça mais sentido a ser feito assim que eu fechar esse módulo de Base técnica :wink: .
