### ISSUE TITLE
[FIX] Adicionar target="_blank" em todos os links

### ISSUE THREAD

**Issue by angelinopires** [angelinopires/career_rush#5]
Estudar a possibilidade de usar o markdown com target blank, caso não for possível utilizar elementos anchor do HTML. 

Exemplo: <a target="_blank" href="link">texto do link</a>

**Comment by juunegreiros** [comment]
Angel, não sei se é uma boa colocar target _blank nesse caso 🤔 
Ele tem vários problemas de acessibilidade e interrompe o fluxo da página, ele é bom de usar em casos mais específicos (como abrir uma midia ou quando o usuário está no meio de algo e não pode perder). Nesse caso, acho legal dar a autonomia pro usuário, se ele quiser, abrir em uma nova aba mesmo. O que acha? Vou deixar [esse link](https://css-tricks.com/use-target_blank/) pra você dar uma olhada também 😊

**Comment by angelinopires** [comment]
É um bom tópico sobre. Só que todos os links que eu adicionei são para conteúdos para serem consumidos externamente, Mesmo assim me convenceu, vou deixar tudo sem blank :)
