### ISSUE TITLE
[FEATURE] Adicionar coluna de recompensa/ganho nas tabelas

### ISSUE THREAD

**Issue by angelinopires** [angelinopires/career_rush#6]
As tabelas são informações mais diretas sobre cada trecho do módulo. Uma ideia interessante que surgiu, foi adicionar uma coluna "recompensa/ganho" pra cada desafio concluído.

Isso pode ser subjetivo, como incrementar uma habilidade, ou até algo físico, como um brinde, dinheiro, ou até uma cerveja. 

Acredito que isso vai trazer mais engajamento pra cada módulo, e uma sensação maior de progresso!

**Comment by juunegreiros** [comment]
Adoro essa ideia! Mas pra isso, teríamos que ter formas de medir o progresso. Talvez alguma avaliação ou algo assim, podemos pensar melhor sobre. Tenho umas ideias pra plataforma nesse sentido, já até falamos sobre, mas podemos conversar melhor depois.
E as recompensas podem até começar com algo como adesivos mesmo, medindo o progresso de forma semelhante ao Hacktoberfest

**Comment by angelinopires** [comment]
@juunegreiros minha ideia é tipo assim:

![image](https://user-images.githubusercontent.com/32209374/73783848-283b2f80-4773-11ea-9b07-b085f3e5c833.png)

O lance das recompensas seria algo como uma habilidade adquirida ou melhorada. Para fazermos o esquema de Stickers ou igual a Hacktoberfest precisariamos de outra estrutura... Mas continuo achando a ideia massa :)

**Comment by angelinopires** [comment]
Quanto ao lance de medir progresso... Pensei em métricas, mas também não tive uma ideia palpável de início, por isso só mantive os desafios... :thinking:
